import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue, Inter, Yusei_Magic, Playfair_Display_SC } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bebas',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const yusei_magic = Yusei_Magic({
    subsets: ['latin'],
    weight: ['400'],
  variable: '--font-yusei-magic', 
});

const playfair_display_sc = Playfair_Display_SC({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-playfair-display-sc',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${geistSans.variable} ${geistMono.variable} ${bebas.variable} ${inter.variable} ${yusei_magic.variable} ${playfair_display_sc.variable} antialiased`}
      >
        {/*<NavBar />*/}
        {children}
        <div className="w-full min-h-96 bg-black text-white">
           footer
        </div>
      </body>
    </html>
  );
}
